run_name: RUN_NAME
seed: 6198
dry_run: false

wandb:
  name: ${run_name}
  project: olmo
  entity: lklab_kaist

model:
  d_model: 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: true  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile: null

optimizer:
  name: adamw
  learning_rate: 1.0e-5
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: constant

tokenizer:
  identifier: tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right

save_folder: ${oc.env:SCRATCH_DIR,no_exist}/checkpoints/${run_name}
remote_save_folder: null
save_overwrite: true
# Sharded checkpoints (best for restarts)
save_interval: 999999
save_num_checkpoints_to_keep: -1
# Unsharded checkpoints (for final storage)
save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: -1

load_path: LOAD_PATH
reset_optimizer_state: true
reset_trainer_state: true
probe_dataset: ${oc.env:SCRATCH_DIR,no_exist}/fictional_knowledge/fictional_knowledge_paraphrased.json
eval_on_load: true

max_duration: 5ep  # 5 epochs
global_train_batch_size: 16
device_train_microbatch_size: 4
time_limit: null

precision: amp_bf16

fsdp:
  wrapping_strategy: by_block
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: 1
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators: []

data_shuffling: false

data:
  pad_direction: right
  num_workers: 16
  drop_last: true
  pin_memory: true
  prefetch_factor: 1
  persistent_workers: true
  timeout: 0
  paths:
    - [DATASET_PATH]